<a href="https://colab.research.google.com/github/tradertanmay/Credit-Risk-Models/blob/master/Probability_of_Default_Model_Building.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aim: To calculate the probability of Default for Single Customer and Also Portfolio level PD

Load the Dataset

Mounting Google Drive

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

# Import Libraries

In [0]:
import numpy as np
import pandas as pd

# Loading the Data and Selecting the Features

### Import Data

In [0]:
loan_data_inputs_train = pd.read_csv('/content/drive/My Drive/PD, LGD,EAD Datasets/loan_data_inputs_train.csv', index_col = 0, engine = "python", encoding='utf-8', error_bad_lines=False)
loan_data_targets_train = pd.read_csv('/content/drive/My Drive/PD, LGD,EAD Datasets/loan_data_targets_train.csv', index_col = 0, header = None, engine = "python", encoding='utf-8', error_bad_lines=False)
loan_data_inputs_test = pd.read_csv('/content/drive/My Drive/PD, LGD,EAD Datasets/loan_data_inputs_test.csv', index_col = 0, engine = "python", encoding='utf-8', error_bad_lines=False)
loan_data_targets_test = pd.read_csv('/content/drive/My Drive/PD, LGD,EAD Datasets/loan_data_targets_test.csv', index_col = 0, header = None, engine = "python", encoding='utf-8', error_bad_lines=False)

### Explore Data

In [6]:
loan_data_inputs_train.head()

        Unnamed: 0.1  ...  mths_since_last_record:>86
427211        427211  ...                           0
206088        206088  ...                           0
136020        136020  ...                           0
412305        412305  ...                           0
36159          36159  ...                           0

[5 rows x 324 columns]

In [7]:
loan_data_targets_train.head()

        1
0
427211  1
206088  1
136020  1
412305  0
36159   0

In [8]:
loan_data_inputs_train.shape

(373028, 324)

In [9]:
loan_data_targets_train.shape

(373028, 1)

In [10]:
loan_data_inputs_test.shape

(93257, 324)

In [11]:
loan_data_targets_test.shape

(93257, 1)

### Selecting the Features

In [0]:
# Following are our Features which we selected using Filter Methods,
# Machine Learning Techniques which  we identified  in preprossesing steps.
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:>=4',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',
'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',
'total_acc:<=27',
'total_acc:28-51',
'total_acc:>=52',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',
'total_rev_hi_lim:>95K',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

In [0]:
# Here we store the names of the reference category dummy variables in a list.
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:>=4',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:<=27',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [14]:
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
# From the dataframe with input variables, we drop the variables with variable names in the list with reference categories. 
inputs_train.head()

        grade:A  ...  mths_since_last_record:>86
427211        1  ...                           0
206088        0  ...                           0
136020        1  ...                           0
412305        0  ...                           0
36159         0  ...                           0

[5 rows x 104 columns]

# PD Model Estimation

## Logistic Regression

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [0]:
reg = LogisticRegression()
# We create an instance of an object from the 'LogisticRegression' class.

In [0]:
pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.

In [18]:
reg.fit(inputs_train, loan_data_targets_train)
# Estimates the coefficients of the object from the 'LogisticRegression' class
# with inputs (independent variables) contained in the first dataframe
# and targets (dependent variables) contained in the second dataframe.

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
reg.intercept_
# Displays the intercept contain in the estimated ("fitted") object from the 'LogisticRegression' class.

array([-1.69952942])

In [20]:
reg.coef_
# Displays the coefficients contained in the estimated ("fitted") object from the 'LogisticRegression' class.

array([[ 1.11564814,  0.87821442,  0.68406102,  0.49615513,  0.32086627,
         0.1327453 ,  0.0913066 ,  0.10674914,  0.03709805,  0.05926675,
         0.06006569,  0.06258239,  0.07863318,  0.13623852,  0.10057918,
         0.18508371,  0.240778  ,  0.22440333,  0.26296412,  0.32120776,
         0.52223795,  0.08812322, -0.01073767,  0.30435317,  0.20089378,
         0.2135425 ,  0.26660124,  0.0540162 ,  0.07926688,  0.10043268,
         0.125459  ,  0.09066922,  0.06056857,  0.1232731 ,  1.07164095,
         0.87127988,  0.77095192,  0.57005078,  0.40856933,  0.16337746,
        -0.07245434,  0.88220606,  0.55485282,  0.30349276,  0.11143723,
         0.05576085,  0.0373835 ,  0.07838188,  0.11904074,  0.12463411,
         0.09024338,  0.0475655 ,  0.66682262,  0.52310363,  0.31371819,
         0.31904893,  0.22250654,  0.19641119,  0.18002347,  0.17849936,
         0.20685208,  0.12092404,  0.1218669 ,  0.15832159, -0.02021198,
         0.02664994,  0.20054101,  0.04260767,  0.01158328,  0.01092695,
         0.02531573,  0.04688789,  0.07275343,  0.22414744, -0.07037246,
        -0.00219072,  0.09553171,  0.16425987,  0.24016002,  0.31388071,
         0.38940537,  0.40803449,  0.48529644,  0.57355493,  0.499868  ,
         0.20487179,  0.33161308,  0.36039974,  0.30082071,  0.2249137 ,
         0.12707112,  0.11606043,  0.08207061,  0.04229935,  0.07238813,
         0.14085071,  0.15168993,  0.1037427 ,  0.3544862 ,  0.44532582,
         0.37884469,  0.54039254,  0.20590027,  0.27077003]])

In [0]:
feature_name = inputs_train.columns.values
# Stores the names of the columns of a dataframe in a variable.

In [22]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
# Creates a dataframe with a column titled 'Feature name' and row values contained in the 'feature_name' variable.
summary_table['Coefficients'] = np.transpose(reg.coef_)
# Creates a new column in the dataframe, called 'Coefficients',
# with row values the transposed coefficients from the 'LogisticRegression' object.
summary_table.index = summary_table.index + 1
# Increases the index of every row of the dataframe with 1.
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# Assigns values of the row with index 0 of the dataframe.
summary_table = summary_table.sort_index()
# Sorts the dataframe by index.
summary_table

                            Feature name  Coefficients
0                              Intercept     -1.699529
1                                grade:A      1.115648
2                                grade:B      0.878214
3                                grade:C      0.684061
4                                grade:D      0.496155
5                                grade:E      0.320866
6                                grade:F      0.132745
7                     home_ownership:OWN      0.091307
8                home_ownership:MORTGAGE      0.106749
9                       addr_state:NM_VA      0.037098
10                         addr_state:NY      0.059267
11          addr_state:OK_TN_MO_LA_MD_NC      0.060066
12                         addr_state:CA      0.062582
13                addr_state:UT_KY_AZ_NJ      0.078633
14             addr_state:AR_MI_PA_OH_MN      0.136239
15             addr_state:RI_MA_DE_SD_IN      0.100579
16                   addr_state:GA_WA_OR      0.185084
17                      addr_state:WI_MT      0.240778
18                         addr_state:TX      0.224403
19                      addr_state:IL_CT      0.262964
20          addr_state:KS_SC_CO_VT_AK_MS      0.321208
21          addr_state:WV_NH_WY_DC_ME_ID      0.522238
22      verification_status:Not Verified      0.088123
23   verification_status:Source Verified     -0.010738
24                   purpose:credit_card      0.304353
25            purpose:debt_consolidation      0.200894
26            purpose:oth__med__vacation      0.213542
27   purpose:major_purch__car__home_impr      0.266601
28                 initial_list_status:w      0.054016
29                               term:36      0.079267
30                          emp_length:1      0.100433
31                        emp_length:2-4      0.125459
32                        emp_length:5-6      0.090669
33                        emp_length:7-9      0.060569
34                         emp_length:10      0.123273
35                mths_since_issue_d:<38      1.071641
36              mths_since_issue_d:38-39      0.871280
37              mths_since_issue_d:40-41      0.770952
38              mths_since_issue_d:42-48      0.570051
39              mths_since_issue_d:49-52      0.408569
40              mths_since_issue_d:53-64      0.163377
41              mths_since_issue_d:65-84     -0.072454
42                       int_rate:<9.548      0.882206
43                 int_rate:9.548-12.025      0.554853
44                 int_rate:12.025-15.74      0.303493
45                 int_rate:15.74-20.281      0.111437
46   mths_since_earliest_cr_line:141-164      0.055761
47   mths_since_earliest_cr_line:165-247      0.037384
48   mths_since_earliest_cr_line:248-270      0.078382
49   mths_since_earliest_cr_line:271-352      0.119041
50      mths_since_earliest_cr_line:>352      0.124634
51                         delinq_2yrs:0      0.090243
52                       delinq_2yrs:1-3      0.047566
53                      inq_last_6mths:0      0.666823
54                    inq_last_6mths:1-2      0.523104
55                    inq_last_6mths:3-6      0.313718
56                          open_acc:1-3      0.319049
57                         open_acc:4-12      0.222507
58                        open_acc:13-17      0.196411
59                        open_acc:18-22      0.180023
60                        open_acc:23-25      0.178499
61                        open_acc:26-30      0.206852
62                         open_acc:>=31      0.120924
63                           pub_rec:3-4      0.121867
64                           pub_rec:>=5      0.158322
65                       total_acc:28-51     -0.020212
66                        total_acc:>=52      0.026650
67                    acc_now_delinq:>=1      0.200541
68               total_rev_hi_lim:5K-10K      0.042608
69              total_rev_hi_lim:10K-20K      0.011583
70              total_rev_hi_lim:20K-30K      0.010927
71              total_rev_hi_lim:30K-40K      0.025316
72              total_rev_hi_lim:40K-55K      0.046888
73              total_rev_hi_lim:55K-95K      0.072753
74                 total_rev_hi_lim:>95K      0.224147
75                    annual_inc:20K-30K     -0.070372
76                    annual_inc:30K-40K     -0.002191
77                    annual_inc:40K-50K      0.095532
78                    annual_inc:50K-60K      0.164260
79                    annual_inc:60K-70K      0.240160
80                    annual_inc:70K-80K      0.313881
81                    annual_inc:80K-90K      0.389405
82                   annual_inc:90K-100K      0.408034
83                  annual_inc:100K-120K      0.485296
84                  annual_inc:120K-140K      0.573555
85                      annual_inc:>140K      0.499868
86                             dti:<=1.4      0.204872
87                           dti:1.4-3.5      0.331613
88                           dti:3.5-7.7      0.360400
89                          dti:7.7-10.5      0.300821
90                         dti:10.5-16.1      0.224914
91                         dti:16.1-20.3      0.127071
92                         dti:20.3-21.7      0.116060
93                         dti:21.7-22.4      0.082071
94                           dti:22.4-35      0.042299
95        mths_since_last_delinq:Missing      0.072388
96           mths_since_last_delinq:4-30      0.140851
97          mths_since_last_delinq:31-56      0.151690
98           mths_since_last_delinq:>=57      0.103743
99        mths_since_last_record:Missing      0.354486
100          mths_since_last_record:3-20      0.445326
101         mths_since_last_record:21-31      0.378845
102         mths_since_last_record:32-80      0.540393
103         mths_since_last_record:81-86      0.205900
104           mths_since_last_record:>86      0.270770

## Build a Logistic Regression Model with P-Values

In [0]:
# P values for sklearn logistic regression.

# Class to display p-values for logistic regression in sklearn.

from sklearn import linear_model
import scipy.stats as stat

class LogisticRegression_with_p_values:
    
    def __init__(self,*args,**kwargs):#,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)#,**args)

    def fit(self,X,y):
        self.model.fit(X,y)
        
        #### Get p-values for the fitted model ####
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X / denom).T,X) ## Fisher Information Matrix
        Cramer_Rao = np.linalg.inv(F_ij) ## Inverse Information Matrix
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates # z-score for eaach model coefficient
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores] ### two tailed test for p-values
        
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        #self.z_scores = z_scores
        self.p_values = p_values
        #self.sigma_estimates = sigma_estimates
        #self.F_ij = F_ij

In [0]:
from sklearn import linear_model
import scipy.stats as stat

class LogisticRegression_with_p_values:
    
    def __init__(self,*args,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)

    def fit(self,X,y):
        self.model.fit(X,y)
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X / denom).T,X)
        Cramer_Rao = np.linalg.inv(F_ij)
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores]
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        self.p_values = p_values

In [0]:
reg = LogisticRegression_with_p_values()
# We create an instance of an object from the newly created 'LogisticRegression_with_p_values()' class.

In [26]:
reg.fit(inputs_train, loan_data_targets_train)
# Estimates the coefficients of the object from the 'LogisticRegression' class
# with inputs (independent variables) contained in the first dataframe
# and targets (dependent variables) contained in the second dataframe.

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [27]:
# Same as above.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                            Feature name  Coefficients
0                              Intercept     -1.699529
1                                grade:A      1.115648
2                                grade:B      0.878214
3                                grade:C      0.684061
4                                grade:D      0.496155
5                                grade:E      0.320866
6                                grade:F      0.132745
7                     home_ownership:OWN      0.091307
8                home_ownership:MORTGAGE      0.106749
9                       addr_state:NM_VA      0.037098
10                         addr_state:NY      0.059267
11          addr_state:OK_TN_MO_LA_MD_NC      0.060066
12                         addr_state:CA      0.062582
13                addr_state:UT_KY_AZ_NJ      0.078633
14             addr_state:AR_MI_PA_OH_MN      0.136239
15             addr_state:RI_MA_DE_SD_IN      0.100579
16                   addr_state:GA_WA_OR      0.185084
17                      addr_state:WI_MT      0.240778
18                         addr_state:TX      0.224403
19                      addr_state:IL_CT      0.262964
20          addr_state:KS_SC_CO_VT_AK_MS      0.321208
21          addr_state:WV_NH_WY_DC_ME_ID      0.522238
22      verification_status:Not Verified      0.088123
23   verification_status:Source Verified     -0.010738
24                   purpose:credit_card      0.304353
25            purpose:debt_consolidation      0.200894
26            purpose:oth__med__vacation      0.213542
27   purpose:major_purch__car__home_impr      0.266601
28                 initial_list_status:w      0.054016
29                               term:36      0.079267
30                          emp_length:1      0.100433
31                        emp_length:2-4      0.125459
32                        emp_length:5-6      0.090669
33                        emp_length:7-9      0.060569
34                         emp_length:10      0.123273
35                mths_since_issue_d:<38      1.071641
36              mths_since_issue_d:38-39      0.871280
37              mths_since_issue_d:40-41      0.770952
38              mths_since_issue_d:42-48      0.570051
39              mths_since_issue_d:49-52      0.408569
40              mths_since_issue_d:53-64      0.163377
41              mths_since_issue_d:65-84     -0.072454
42                       int_rate:<9.548      0.882206
43                 int_rate:9.548-12.025      0.554853
44                 int_rate:12.025-15.74      0.303493
45                 int_rate:15.74-20.281      0.111437
46   mths_since_earliest_cr_line:141-164      0.055761
47   mths_since_earliest_cr_line:165-247      0.037384
48   mths_since_earliest_cr_line:248-270      0.078382
49   mths_since_earliest_cr_line:271-352      0.119041
50      mths_since_earliest_cr_line:>352      0.124634
51                         delinq_2yrs:0      0.090243
52                       delinq_2yrs:1-3      0.047566
53                      inq_last_6mths:0      0.666823
54                    inq_last_6mths:1-2      0.523104
55                    inq_last_6mths:3-6      0.313718
56                          open_acc:1-3      0.319049
57                         open_acc:4-12      0.222507
58                        open_acc:13-17      0.196411
59                        open_acc:18-22      0.180023
60                        open_acc:23-25      0.178499
61                        open_acc:26-30      0.206852
62                         open_acc:>=31      0.120924
63                           pub_rec:3-4      0.121867
64                           pub_rec:>=5      0.158322
65                       total_acc:28-51     -0.020212
66                        total_acc:>=52      0.026650
67                    acc_now_delinq:>=1      0.200541
68               total_rev_hi_lim:5K-10K      0.042608
69              total_rev_hi_lim:10K-20K      0.011583
70              total_rev_hi_lim:20K-30K      0.010927
71              total_rev_hi_lim:30K-40K      0.025316
72              total_rev_hi_lim:40K-55K      0.046888
73              total_rev_hi_lim:55K-95K      0.072753
74                 total_rev_hi_lim:>95K      0.224147
75                    annual_inc:20K-30K     -0.070372
76                    annual_inc:30K-40K     -0.002191
77                    annual_inc:40K-50K      0.095532
78                    annual_inc:50K-60K      0.164260
79                    annual_inc:60K-70K      0.240160
80                    annual_inc:70K-80K      0.313881
81                    annual_inc:80K-90K      0.389405
82                   annual_inc:90K-100K      0.408034
83                  annual_inc:100K-120K      0.485296
84                  annual_inc:120K-140K      0.573555
85                      annual_inc:>140K      0.499868
86                             dti:<=1.4      0.204872
87                           dti:1.4-3.5      0.331613
88                           dti:3.5-7.7      0.360400
89                          dti:7.7-10.5      0.300821
90                         dti:10.5-16.1      0.224914
91                         dti:16.1-20.3      0.127071
92                         dti:20.3-21.7      0.116060
93                         dti:21.7-22.4      0.082071
94                           dti:22.4-35      0.042299
95        mths_since_last_delinq:Missing      0.072388
96           mths_since_last_delinq:4-30      0.140851
97          mths_since_last_delinq:31-56      0.151690
98           mths_since_last_delinq:>=57      0.103743
99        mths_since_last_record:Missing      0.354486
100          mths_since_last_record:3-20      0.445326
101         mths_since_last_record:21-31      0.378845
102         mths_since_last_record:32-80      0.540393
103         mths_since_last_record:81-86      0.205900
104           mths_since_last_record:>86      0.270770

In [0]:
# This is a list.
p_values = reg.p_values
# We take the result of the newly added method 'p_values' and store it in a variable 'p_values'.

In [0]:
# Add the intercept for completeness.
p_values = np.append(np.nan, np.array(p_values))
# We add the value 'NaN' in the beginning of the variable with p-values.

In [0]:
summary_table['p_values'] = p_values
# In the 'summary_table' dataframe, we add a new column, called 'p_values', containing the values from the 'p_values' variable.

In [31]:
summary_table

                            Feature name  Coefficients       p_values
0                              Intercept     -1.699529            NaN
1                                grade:A      1.115648   1.395530e-34
2                                grade:B      0.878214   1.052416e-46
3                                grade:C      0.684061   1.797961e-33
4                                grade:D      0.496155   3.299355e-20
5                                grade:E      0.320866   2.729572e-11
6                                grade:F      0.132745   8.210693e-03
7                     home_ownership:OWN      0.091307   6.062745e-06
8                home_ownership:MORTGAGE      0.106749   4.307547e-17
9                       addr_state:NM_VA      0.037098   2.473405e-01
10                         addr_state:NY      0.059267   1.469878e-02
11          addr_state:OK_TN_MO_LA_MD_NC      0.060066   9.661192e-03
12                         addr_state:CA      0.062582   3.223486e-03
13                addr_state:UT_KY_AZ_NJ      0.078633   1.630373e-03
14             addr_state:AR_MI_PA_OH_MN      0.136239   1.615507e-09
15             addr_state:RI_MA_DE_SD_IN      0.100579   7.632719e-04
16                   addr_state:GA_WA_OR      0.185084   4.292914e-12
17                      addr_state:WI_MT      0.240778   4.226364e-07
18                         addr_state:TX      0.224403   6.549649e-18
19                      addr_state:IL_CT      0.262964   2.566084e-19
20          addr_state:KS_SC_CO_VT_AK_MS      0.321208   2.425607e-25
21          addr_state:WV_NH_WY_DC_ME_ID      0.522238   1.027728e-22
22      verification_status:Not Verified      0.088123   2.092092e-09
23   verification_status:Source Verified     -0.010738   4.255392e-01
24                   purpose:credit_card      0.304353   1.038385e-26
25            purpose:debt_consolidation      0.200894   1.634876e-14
26            purpose:oth__med__vacation      0.213542   8.204530e-12
27   purpose:major_purch__car__home_impr      0.266601   1.939686e-17
28                 initial_list_status:w      0.054016   3.522061e-05
29                               term:36      0.079267   2.278908e-08
30                          emp_length:1      0.100433   1.097624e-04
31                        emp_length:2-4      0.125459   3.134543e-11
32                        emp_length:5-6      0.090669   2.303318e-05
33                        emp_length:7-9      0.060569   3.609365e-03
34                         emp_length:10      0.123273   2.359853e-11
35                mths_since_issue_d:<38      1.071641  7.027699e-170
36              mths_since_issue_d:38-39      0.871280  7.923616e-140
37              mths_since_issue_d:40-41      0.770952  3.582790e-115
38              mths_since_issue_d:42-48      0.570051   3.003252e-80
39              mths_since_issue_d:49-52      0.408569   2.618156e-37
40              mths_since_issue_d:53-64      0.163377   6.001576e-08
41              mths_since_issue_d:65-84     -0.072454   1.354891e-02
42                       int_rate:<9.548      0.882206   7.100822e-31
43                 int_rate:9.548-12.025      0.554853   5.005441e-35
44                 int_rate:12.025-15.74      0.303493   2.187642e-16
45                 int_rate:15.74-20.281      0.111437   1.313977e-04
46   mths_since_earliest_cr_line:141-164      0.055761   2.562702e-02
47   mths_since_earliest_cr_line:165-247      0.037384   6.658282e-02
48   mths_since_earliest_cr_line:248-270      0.078382   3.229018e-03
49   mths_since_earliest_cr_line:271-352      0.119041   6.463308e-07
50      mths_since_earliest_cr_line:>352      0.124634   4.095856e-06
51                         delinq_2yrs:0      0.090243   1.121709e-01
52                       delinq_2yrs:1-3      0.047566   3.731201e-01
53                      inq_last_6mths:0      0.666823   5.607824e-09
54                    inq_last_6mths:1-2      0.523104   4.687049e-06
55                    inq_last_6mths:3-6      0.313718   6.258164e-03
56                          open_acc:1-3      0.319049   5.211245e-02
57                         open_acc:4-12      0.222507   1.656286e-01
58                        open_acc:13-17      0.196411   2.219723e-01
59                        open_acc:18-22      0.180023   2.659375e-01
60                        open_acc:23-25      0.178499   2.836904e-01
61                        open_acc:26-30      0.206852   2.285274e-01
62                         open_acc:>=31      0.120924   5.151494e-01
63                           pub_rec:3-4      0.121867   1.984640e-01
64                           pub_rec:>=5      0.158322   4.077531e-01
65                       total_acc:28-51     -0.020212   1.548288e-01
66                        total_acc:>=52      0.026650   5.026340e-01
67                    acc_now_delinq:>=1      0.200541   5.941900e-02
68               total_rev_hi_lim:5K-10K      0.042608   8.361819e-02
69              total_rev_hi_lim:10K-20K      0.011583   6.275373e-01
70              total_rev_hi_lim:20K-30K      0.010927   6.770861e-01
71              total_rev_hi_lim:30K-40K      0.025316   3.900614e-01
72              total_rev_hi_lim:40K-55K      0.046888   1.449038e-01
73              total_rev_hi_lim:55K-95K      0.072753   4.354203e-02
74                 total_rev_hi_lim:>95K      0.224147   7.634966e-05
75                    annual_inc:20K-30K     -0.070372   1.017428e-01
76                    annual_inc:30K-40K     -0.002191   9.579070e-01
77                    annual_inc:40K-50K      0.095532   2.149450e-02
78                    annual_inc:50K-60K      0.164260   9.691414e-05
79                    annual_inc:60K-70K      0.240160   2.605941e-08
80                    annual_inc:70K-80K      0.313881   1.046128e-12
81                    annual_inc:80K-90K      0.389405   2.086492e-17
82                   annual_inc:90K-100K      0.408034   8.386458e-18
83                  annual_inc:100K-120K      0.485296   8.403369e-25
84                  annual_inc:120K-140K      0.573555   6.777237e-27
85                      annual_inc:>140K      0.499868   7.023307e-24
86                             dti:<=1.4      0.204872   2.046258e-02
87                           dti:1.4-3.5      0.331613   9.356431e-06
88                           dti:3.5-7.7      0.360400   3.364320e-08
89                          dti:7.7-10.5      0.300821   3.322504e-06
90                         dti:10.5-16.1      0.224914   3.352695e-04
91                         dti:16.1-20.3      0.127071   4.263042e-02
92                         dti:20.3-21.7      0.116060   7.477239e-02
93                         dti:21.7-22.4      0.082071   2.339030e-01
94                           dti:22.4-35      0.042299   4.945824e-01
95        mths_since_last_delinq:Missing      0.072388   2.081964e-01
96           mths_since_last_delinq:4-30      0.140851   8.047546e-03
97          mths_since_last_delinq:31-56      0.151690   9.633562e-03
98           mths_since_last_delinq:>=57      0.103743   8.247097e-02
99        mths_since_last_record:Missing      0.354486   3.679170e-05
100          mths_since_last_record:3-20      0.445326   4.456358e-04
101         mths_since_last_record:21-31      0.378845   1.149971e-03
102         mths_since_last_record:32-80      0.540393   1.955500e-09
103         mths_since_last_record:81-86      0.205900   5.220759e-02
104           mths_since_last_record:>86      0.270770   2.245025e-03

In [0]:
# We are going to remove some features, the coefficients for all or almost all of the dummy variables for which,
# are not tatistically significant.

# We do that by specifying another list of dummy variables as reference categories, and a list of variables to remove.
# Then, we are going to drop the two datasets from the original list of dummy variables.

# Variables
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [33]:
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
inputs_train.head()

        grade:A  ...  mths_since_last_record:>86
427211        1  ...                           0
206088        0  ...                           0
136020        1  ...                           0
412305        0  ...                           0
36159         0  ...                           0

[5 rows x 84 columns]

In [34]:
# Here we run a new model.
reg2 = LogisticRegression_with_p_values()
reg2.fit(inputs_train, loan_data_targets_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [0]:
feature_name = inputs_train.columns.values

In [36]:
# Same as above.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg2.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                           Feature name  Coefficients
0                             Intercept     -1.385359
1                               grade:A      1.121517
2                               grade:B      0.881489
3                               grade:C      0.687847
4                               grade:D      0.500470
5                               grade:E      0.325084
6                               grade:F      0.137041
7                    home_ownership:OWN      0.093504
8               home_ownership:MORTGAGE      0.105992
9                      addr_state:NM_VA      0.037052
10                        addr_state:NY      0.057065
11         addr_state:OK_TN_MO_LA_MD_NC      0.059630
12                        addr_state:CA      0.063601
13               addr_state:UT_KY_AZ_NJ      0.078480
14            addr_state:AR_MI_PA_OH_MN      0.135479
15            addr_state:RI_MA_DE_SD_IN      0.100868
16                  addr_state:GA_WA_OR      0.185782
17                     addr_state:WI_MT      0.240481
18                        addr_state:TX      0.222370
19                     addr_state:IL_CT      0.261843
20         addr_state:KS_SC_CO_VT_AK_MS      0.320738
21         addr_state:WV_NH_WY_DC_ME_ID      0.522257
22     verification_status:Not Verified      0.085872
23  verification_status:Source Verified     -0.010918
24                  purpose:credit_card      0.301414
25           purpose:debt_consolidation      0.197791
26           purpose:oth__med__vacation      0.213351
27  purpose:major_purch__car__home_impr      0.265438
28                initial_list_status:w      0.054412
29                              term:36      0.078523
30                         emp_length:1      0.099322
31                       emp_length:2-4      0.125183
32                       emp_length:5-6      0.090508
33                       emp_length:7-9      0.060713
34                        emp_length:10      0.124818
35               mths_since_issue_d:<38      1.076652
36             mths_since_issue_d:38-39      0.874364
37             mths_since_issue_d:40-41      0.773139
38             mths_since_issue_d:42-48      0.572741
39             mths_since_issue_d:49-52      0.411662
40             mths_since_issue_d:53-64      0.166243
41             mths_since_issue_d:65-84     -0.074978
42                      int_rate:<9.548      0.889341
43                int_rate:9.548-12.025      0.559779
44                int_rate:12.025-15.74      0.306814
45                int_rate:15.74-20.281      0.113394
46  mths_since_earliest_cr_line:141-164      0.054001
47  mths_since_earliest_cr_line:165-247      0.034964
48  mths_since_earliest_cr_line:248-270      0.076718
49  mths_since_earliest_cr_line:271-352      0.119311
50     mths_since_earliest_cr_line:>352      0.127038
51                     inq_last_6mths:0      0.667270
52                   inq_last_6mths:1-2      0.520849
53                   inq_last_6mths:3-6      0.310246
54                   acc_now_delinq:>=1      0.193328
55                   annual_inc:20K-30K     -0.076550
56                   annual_inc:30K-40K     -0.013043
57                   annual_inc:40K-50K      0.081670
58                   annual_inc:50K-60K      0.148742
59                   annual_inc:60K-70K      0.224317
60                   annual_inc:70K-80K      0.298258
61                   annual_inc:80K-90K      0.374168
62                  annual_inc:90K-100K      0.393907
63                 annual_inc:100K-120K      0.472349
64                 annual_inc:120K-140K      0.563197
65                     annual_inc:>140K      0.499155
66                            dti:<=1.4      0.245696
67                          dti:1.4-3.5      0.361012
68                          dti:3.5-7.7      0.379473
69                         dti:7.7-10.5      0.314818
70                        dti:10.5-16.1      0.235982
71                        dti:16.1-20.3      0.134796
72                        dti:20.3-21.7      0.122542
73                        dti:21.7-22.4      0.087628
74                          dti:22.4-35      0.045895
75       mths_since_last_delinq:Missing      0.116769
76          mths_since_last_delinq:4-30      0.143818
77         mths_since_last_delinq:31-56      0.189956
78          mths_since_last_delinq:>=57      0.142873
79       mths_since_last_record:Missing      0.324805
80          mths_since_last_record:3-20      0.435911
81         mths_since_last_record:21-31      0.357053
82         mths_since_last_record:32-80      0.509906
83         mths_since_last_record:81-86      0.171735
84           mths_since_last_record:>86      0.237597

In [37]:
# We add the 'p_values' here, just as we did before.
p_values = reg2.p_values
p_values = np.append(np.nan,np.array(p_values))
summary_table['p_values'] = p_values
summary_table
# Here we get the results for our final PD model.

                           Feature name  Coefficients       p_values
0                             Intercept     -1.385359            NaN
1                               grade:A      1.121517   4.754644e-35
2                               grade:B      0.881489   2.167958e-47
3                               grade:C      0.687847   3.274807e-34
4                               grade:D      0.500470   6.938923e-21
5                               grade:E      0.325084   5.877966e-12
6                               grade:F      0.137041   5.231479e-03
7                    home_ownership:OWN      0.093504   3.463432e-06
8               home_ownership:MORTGAGE      0.105992   5.250748e-17
9                      addr_state:NM_VA      0.037052   2.472992e-01
10                        addr_state:NY      0.057065   1.846239e-02
11         addr_state:OK_TN_MO_LA_MD_NC      0.059630   9.997575e-03
12                        addr_state:CA      0.063601   2.693518e-03
13               addr_state:UT_KY_AZ_NJ      0.078480   1.630267e-03
14            addr_state:AR_MI_PA_OH_MN      0.135479   1.793285e-09
15            addr_state:RI_MA_DE_SD_IN      0.100868   7.237441e-04
16                  addr_state:GA_WA_OR      0.185782   3.244108e-12
17                     addr_state:WI_MT      0.240481   4.262605e-07
18                        addr_state:TX      0.222370   1.127931e-17
19                     addr_state:IL_CT      0.261843   3.088912e-19
20         addr_state:KS_SC_CO_VT_AK_MS      0.320738   2.438585e-25
21         addr_state:WV_NH_WY_DC_ME_ID      0.522257   9.641643e-23
22     verification_status:Not Verified      0.085872   4.102888e-09
23  verification_status:Source Verified     -0.010918   4.162421e-01
24                  purpose:credit_card      0.301414   1.494194e-26
25           purpose:debt_consolidation      0.197791   2.744820e-14
26           purpose:oth__med__vacation      0.213351   6.907150e-12
27  purpose:major_purch__car__home_impr      0.265438   1.846974e-17
28                initial_list_status:w      0.054412   3.071709e-05
29                              term:36      0.078523   1.942302e-08
30                         emp_length:1      0.099322   1.283516e-04
31                       emp_length:2-4      0.125183   3.298866e-11
32                       emp_length:5-6      0.090508   2.349566e-05
33                       emp_length:7-9      0.060713   3.512644e-03
34                        emp_length:10      0.124818   1.283447e-11
35               mths_since_issue_d:<38      1.076652  1.299999e-178
36             mths_since_issue_d:38-39      0.874364  5.866071e-148
37             mths_since_issue_d:40-41      0.773139  2.883696e-122
38             mths_since_issue_d:42-48      0.572741   2.867664e-86
39             mths_since_issue_d:49-52      0.411662   5.202592e-40
40             mths_since_issue_d:53-64      0.166243   1.287128e-08
41             mths_since_issue_d:65-84     -0.074978   1.038574e-02
42                      int_rate:<9.548      0.889341   1.599347e-31
43                int_rate:9.548-12.025      0.559779   4.325695e-36
44                int_rate:12.025-15.74      0.306814   6.208629e-17
45                int_rate:15.74-20.281      0.113394   9.074229e-05
46  mths_since_earliest_cr_line:141-164      0.054001   2.997792e-02
47  mths_since_earliest_cr_line:165-247      0.034964   8.174102e-02
48  mths_since_earliest_cr_line:248-270      0.076718   3.459925e-03
49  mths_since_earliest_cr_line:271-352      0.119311   3.533180e-07
50     mths_since_earliest_cr_line:>352      0.127038   1.665946e-06
51                     inq_last_6mths:0      0.667270   3.185347e-14
52                   inq_last_6mths:1-2      0.520849   2.985863e-09
53                   inq_last_6mths:3-6      0.310246   4.457780e-04
54                   acc_now_delinq:>=1      0.193328   6.837018e-02
55                   annual_inc:20K-30K     -0.076550   6.883939e-02
56                   annual_inc:30K-40K     -0.013043   7.469618e-01
57                   annual_inc:40K-50K      0.081670   4.307047e-02
58                   annual_inc:50K-60K      0.148742   2.753749e-04
59                   annual_inc:60K-70K      0.224317   8.150266e-08
60                   annual_inc:70K-80K      0.298258   2.713726e-12
61                   annual_inc:80K-90K      0.374168   3.700638e-17
62                  annual_inc:90K-100K      0.393907   1.108271e-17
63                 annual_inc:100K-120K      0.472349   3.990955e-25
64                 annual_inc:120K-140K      0.563197   1.891485e-27
65                     annual_inc:>140K      0.499155   8.326916e-26
66                            dti:<=1.4      0.245696   3.210874e-03
67                          dti:1.4-3.5      0.361012   2.478496e-07
68                          dti:3.5-7.7      0.379473   3.097993e-10
69                         dti:7.7-10.5      0.314818   1.490529e-07
70                        dti:10.5-16.1      0.235982   4.601037e-05
71                        dti:16.1-20.3      0.134796   2.011066e-02
72                        dti:20.3-21.7      0.122542   4.350994e-02
73                        dti:21.7-22.4      0.087628   1.761260e-01
74                          dti:22.4-35      0.045895   4.233066e-01
75       mths_since_last_delinq:Missing      0.116769   2.514763e-02
76          mths_since_last_delinq:4-30      0.143818   6.337492e-03
77         mths_since_last_delinq:31-56      0.189956   3.711883e-04
78          mths_since_last_delinq:>=57      0.142873   8.924871e-03
79       mths_since_last_record:Missing      0.324805   6.400011e-05
80          mths_since_last_record:3-20      0.435911   3.757484e-04
81         mths_since_last_record:21-31      0.357053   1.509735e-03
82         mths_since_last_record:32-80      0.509906   2.356568e-09
83         mths_since_last_record:81-86      0.171735   9.309364e-02
84           mths_since_last_record:>86      0.237597   4.739917e-03

In [0]:
import pickle

In [0]:
pickle.dump(reg2, open('pd_model.sav', 'wb'))
# Here we export our model to a 'SAV' file with file name 'pd_model.sav'.